---
- name: Deploy Docker App
  hosts: localhost
  become: yes
  connection: local

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull app image
      docker_image:
        name: myapp:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: myapp
        image: myapp:latest
        state: started
        ports:
          - "8080:80"
